### PR TITLE
Update & reboot function

### PR DESCRIPTION
**Pull request by lorenzing**
Hi, 
I thought it might be useful to have a function to update the server directly from the web interface and possibly a function to reboot the companion computer.
The server updater script rpanion-updater.sh:
```
#!/bin/bash

cd Rpanion-server
git pull https://github.com/stephendade/Rpanion-server.git
echo "Update Rpanion-server complete"
```
I have not yet pulled the web interface but only the functions, because I do not know if it is useful for you.

Thank you so much
Lorenzo

### CODE REVIEW

**Comment by lorenzing** [comment]
I improved the script that can help novice users pull to new versions: https://github.com/lorenzing/Rpanion-updater
Waiting for an official integration in the web interface if it's considered useful.

Thank you so much and have a nice day
Lorenzo

**Comment by stephendade** [comment]
There's actually an updater script in https://github.com/stephendade/Rpanion-server/blob/master/deploy/upgrade.sh

The functions you've added in ``aboutinfo.js`` are good, you'll just need to edit them to use the script above.

**Comment by lorenzing** [comment]
Hi Stephen, I'm sorry, I didn't see the built-in update function, with this commit I use that function. Thank you so much

**Comment by stephendade** [comment]
Great. You'll just need to remove the "sudo" from ``'sudo cd ./deploy && ./upgrade.sh'``, as it's not required.

**Comment by stephendade** [comment]
Thanks - I'll merge it in

**Pull request merged**
