### PR TITLE
Adhoc improvements

### LINKED ISSUE #137: Adhoc Wifi does not ask for a gateway
In addition to not saving the configuration between boots, the ad hoc network does not ask for a gateway. I find it very useful to have a gateway to share the internet between nodes.

Here I do it there by /etc/network/interfaces

### PR DESCRIPTION
**Pull request by stephendade**
Fixes #137 and #116

### CODE REVIEW

**Comment by stephendade** [comment]
@brunoolivieri - this adds a gateway field to the Adhoc Wifi config and persists the Adhoc configuration across reboots. Can you test this for me?

**Comment by brunoolivieri** [comment]
Sure, I will test it.

**Comment by brunoolivieri** [comment]
I could set the configuration this time:

image

**Comment by brunoolivieri** [comment]
I set up a setup bed and:


0) I could not connect the Rpanion RPI on the ad-hoc network in the lab like I did last time with the previous version. I need to check it better.  (did you change something?)

1) If it reboots and Rpanion does not start, the configuration is always to an AP on 10.0.2.100.  :-(

2) If the Rpanion starts well, the configuration is re-reset up to the ad-hoc previously setup. :-D   (it is supposed to always force the netmask to 255.255.0.0?)

**Comment by stephendade** [comment]
> If it reboots and Rpanion does not start, the configuration is always to an AP on 10.0.2.100. :-(

Rpanion-server itself sets up the adhoc network when started. I couldn't find a method to otherwise make it persist between reboots.

> If the Rpanion starts well, the configuration is re-reset up to the ad-hoc previously setup. :-D (it is supposed to always force the netmask to 255.255.0.0?)

Yes, netmask is forced to 255.255.0.0. I can hard set to 255.255.255.0 instead, if you want.

> I could not connect the Rpanion RPI on the ad-hoc network in the lab like I did last time with the previous version. I need to check it better. (did you change something?)

Only thing I added was the gateway via ``sudo route add default gw ' + settings.gateway + ' ' + device`` and the persist-network-across-reboots.

Does the ``app.log`` show any errors?

**Pull request merged**
